source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.7.1'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'

gem 'pry-byebug'
gem 'pry-rails'
gem 'rspec-rails'

group :test do
  gem 'tender_spec', path: '../..'
end
